// Code generated by protoc-gen-go. DO NOT EDIT.
// source: baton.proto

package batonpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action int32

const (
	Action_PUB Action = 0
	Action_SUB Action = 1
)

var Action_name = map[int32]string{
	0: "PUB",
	1: "SUB",
}

var Action_value = map[string]int32{
	"PUB": 0,
	"SUB": 1,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{0}
}

type Permission int32

const (
	Permission_READ       Permission = 0
	Permission_WRITE      Permission = 1
	Permission_READ_WRITE Permission = 2
	Permission_DENIED     Permission = 3
)

var Permission_name = map[int32]string{
	0: "READ",
	1: "WRITE",
	2: "READ_WRITE",
	3: "DENIED",
}

var Permission_value = map[string]int32{
	"READ":       0,
	"WRITE":      1,
	"READ_WRITE": 2,
	"DENIED":     3,
}

func (x Permission) String() string {
	return proto.EnumName(Permission_name, int32(x))
}

func (Permission) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{1}
}

type Code int32

const (
	Code_SUCCESS                    Code = 0
	Code_FAILED                     Code = 1
	Code_TOPIC_MISSING              Code = 2
	Code_SUBSCRIPTION_MISSING       Code = 3
	Code_TOPIC_ALREADY_EXIST        Code = 4
	Code_SUBSCRIPTION_ALREADY_EXIST Code = 5
)

var Code_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
	2: "TOPIC_MISSING",
	3: "SUBSCRIPTION_MISSING",
	4: "TOPIC_ALREADY_EXIST",
	5: "SUBSCRIPTION_ALREADY_EXIST",
}

var Code_value = map[string]int32{
	"SUCCESS":                    0,
	"FAILED":                     1,
	"TOPIC_MISSING":              2,
	"SUBSCRIPTION_MISSING":       3,
	"TOPIC_ALREADY_EXIST":        4,
	"SUBSCRIPTION_ALREADY_EXIST": 5,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}

func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{2}
}

type CreateTopicRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	QueueNumbers         int32    `protobuf:"varint,2,opt,name=queueNumbers,proto3" json:"queueNumbers,omitempty"`
	AutoScaling          bool     `protobuf:"varint,3,opt,name=autoScaling,proto3" json:"autoScaling,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicRequest) Reset()         { *m = CreateTopicRequest{} }
func (m *CreateTopicRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTopicRequest) ProtoMessage()    {}
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{0}
}

func (m *CreateTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicRequest.Unmarshal(m, b)
}
func (m *CreateTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicRequest.Marshal(b, m, deterministic)
}
func (m *CreateTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicRequest.Merge(m, src)
}
func (m *CreateTopicRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTopicRequest.Size(m)
}
func (m *CreateTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicRequest proto.InternalMessageInfo

func (m *CreateTopicRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTopicRequest) GetQueueNumbers() int32 {
	if m != nil {
		return m.QueueNumbers
	}
	return 0
}

func (m *CreateTopicRequest) GetAutoScaling() bool {
	if m != nil {
		return m.AutoScaling
	}
	return false
}

type DeleteTopicRequest struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTopicRequest) Reset()         { *m = DeleteTopicRequest{} }
func (m *DeleteTopicRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTopicRequest) ProtoMessage()    {}
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{1}
}

func (m *DeleteTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTopicRequest.Unmarshal(m, b)
}
func (m *DeleteTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTopicRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTopicRequest.Merge(m, src)
}
func (m *DeleteTopicRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTopicRequest.Size(m)
}
func (m *DeleteTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTopicRequest proto.InternalMessageInfo

func (m *DeleteTopicRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type CreateSubscriptionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topicName,proto3" json:"topicName,omitempty"`
	AutoScaling          bool     `protobuf:"varint,3,opt,name=autoScaling,proto3" json:"autoScaling,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionRequest) Reset()         { *m = CreateSubscriptionRequest{} }
func (m *CreateSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionRequest) ProtoMessage()    {}
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{2}
}

func (m *CreateSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionRequest.Unmarshal(m, b)
}
func (m *CreateSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionRequest.Merge(m, src)
}
func (m *CreateSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionRequest.Size(m)
}
func (m *CreateSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionRequest proto.InternalMessageInfo

func (m *CreateSubscriptionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSubscriptionRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *CreateSubscriptionRequest) GetAutoScaling() bool {
	if m != nil {
		return m.AutoScaling
	}
	return false
}

type DeleteSubscriptionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSubscriptionRequest) Reset()         { *m = DeleteSubscriptionRequest{} }
func (m *DeleteSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSubscriptionRequest) ProtoMessage()    {}
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{3}
}

func (m *DeleteSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSubscriptionRequest.Unmarshal(m, b)
}
func (m *DeleteSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSubscriptionRequest.Merge(m, src)
}
func (m *DeleteSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSubscriptionRequest.Size(m)
}
func (m *DeleteSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSubscriptionRequest proto.InternalMessageInfo

func (m *DeleteSubscriptionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterBrokerRequest struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterBrokerRequest) Reset()         { *m = RegisterBrokerRequest{} }
func (m *RegisterBrokerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterBrokerRequest) ProtoMessage()    {}
func (*RegisterBrokerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{4}
}

func (m *RegisterBrokerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterBrokerRequest.Unmarshal(m, b)
}
func (m *RegisterBrokerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterBrokerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterBrokerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterBrokerRequest.Merge(m, src)
}
func (m *RegisterBrokerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterBrokerRequest.Size(m)
}
func (m *RegisterBrokerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterBrokerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterBrokerRequest proto.InternalMessageInfo

func (m *RegisterBrokerRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type RegisterBrokerResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterBrokerResponse) Reset()         { *m = RegisterBrokerResponse{} }
func (m *RegisterBrokerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterBrokerResponse) ProtoMessage()    {}
func (*RegisterBrokerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{5}
}

func (m *RegisterBrokerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterBrokerResponse.Unmarshal(m, b)
}
func (m *RegisterBrokerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterBrokerResponse.Marshal(b, m, deterministic)
}
func (m *RegisterBrokerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterBrokerResponse.Merge(m, src)
}
func (m *RegisterBrokerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterBrokerResponse.Size(m)
}
func (m *RegisterBrokerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterBrokerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterBrokerResponse proto.InternalMessageInfo

func (m *RegisterBrokerResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BrokerHBRequest struct {
	BrokerId             uint64   `protobuf:"varint,3,opt,name=brokerId,proto3" json:"brokerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerHBRequest) Reset()         { *m = BrokerHBRequest{} }
func (m *BrokerHBRequest) String() string { return proto.CompactTextString(m) }
func (*BrokerHBRequest) ProtoMessage()    {}
func (*BrokerHBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{6}
}

func (m *BrokerHBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerHBRequest.Unmarshal(m, b)
}
func (m *BrokerHBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerHBRequest.Marshal(b, m, deterministic)
}
func (m *BrokerHBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerHBRequest.Merge(m, src)
}
func (m *BrokerHBRequest) XXX_Size() int {
	return xxx_messageInfo_BrokerHBRequest.Size(m)
}
func (m *BrokerHBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerHBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerHBRequest proto.InternalMessageInfo

func (m *BrokerHBRequest) GetBrokerId() uint64 {
	if m != nil {
		return m.BrokerId
	}
	return 0
}

type BrokerHBResponse struct {
	Queues               []uint64 `protobuf:"varint,1,rep,packed,name=queues,proto3" json:"queues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerHBResponse) Reset()         { *m = BrokerHBResponse{} }
func (m *BrokerHBResponse) String() string { return proto.CompactTextString(m) }
func (*BrokerHBResponse) ProtoMessage()    {}
func (*BrokerHBResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{7}
}

func (m *BrokerHBResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerHBResponse.Unmarshal(m, b)
}
func (m *BrokerHBResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerHBResponse.Marshal(b, m, deterministic)
}
func (m *BrokerHBResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerHBResponse.Merge(m, src)
}
func (m *BrokerHBResponse) XXX_Size() int {
	return xxx_messageInfo_BrokerHBResponse.Size(m)
}
func (m *BrokerHBResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerHBResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerHBResponse proto.InternalMessageInfo

func (m *BrokerHBResponse) GetQueues() []uint64 {
	if m != nil {
		return m.Queues
	}
	return nil
}

type UpdateRouteRequest struct {
	// consumerId or producerId
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Action               Action   `protobuf:"varint,3,opt,name=action,proto3,enum=batonpb.Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRouteRequest) Reset()         { *m = UpdateRouteRequest{} }
func (m *UpdateRouteRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRouteRequest) ProtoMessage()    {}
func (*UpdateRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{8}
}

func (m *UpdateRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRouteRequest.Unmarshal(m, b)
}
func (m *UpdateRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRouteRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRouteRequest.Merge(m, src)
}
func (m *UpdateRouteRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRouteRequest.Size(m)
}
func (m *UpdateRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRouteRequest proto.InternalMessageInfo

func (m *UpdateRouteRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRouteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRouteRequest) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_PUB
}

type UpdateRouteResponse struct {
	// consumerId or producerId
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Leases               []*Lease `protobuf:"bytes,2,rep,name=leases,proto3" json:"leases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRouteResponse) Reset()         { *m = UpdateRouteResponse{} }
func (m *UpdateRouteResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRouteResponse) ProtoMessage()    {}
func (*UpdateRouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{9}
}

func (m *UpdateRouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRouteResponse.Unmarshal(m, b)
}
func (m *UpdateRouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRouteResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRouteResponse.Merge(m, src)
}
func (m *UpdateRouteResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRouteResponse.Size(m)
}
func (m *UpdateRouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRouteResponse proto.InternalMessageInfo

func (m *UpdateRouteResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRouteResponse) GetLeases() []*Lease {
	if m != nil {
		return m.Leases
	}
	return nil
}

type Lease struct {
	BrokerId             uint64     `protobuf:"varint,1,opt,name=brokerId,proto3" json:"brokerId,omitempty"`
	BrokerAddr           string     `protobuf:"bytes,2,opt,name=brokerAddr,proto3" json:"brokerAddr,omitempty"`
	ExpiredTime          uint64     `protobuf:"varint,3,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"`
	Perm                 Permission `protobuf:"varint,4,opt,name=perm,proto3,enum=batonpb.Permission" json:"perm,omitempty"`
	QueueId              uint64     `protobuf:"varint,5,opt,name=queueId,proto3" json:"queueId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Lease) Reset()         { *m = Lease{} }
func (m *Lease) String() string { return proto.CompactTextString(m) }
func (*Lease) ProtoMessage()    {}
func (*Lease) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{10}
}

func (m *Lease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lease.Unmarshal(m, b)
}
func (m *Lease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lease.Marshal(b, m, deterministic)
}
func (m *Lease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lease.Merge(m, src)
}
func (m *Lease) XXX_Size() int {
	return xxx_messageInfo_Lease.Size(m)
}
func (m *Lease) XXX_DiscardUnknown() {
	xxx_messageInfo_Lease.DiscardUnknown(m)
}

var xxx_messageInfo_Lease proto.InternalMessageInfo

func (m *Lease) GetBrokerId() uint64 {
	if m != nil {
		return m.BrokerId
	}
	return 0
}

func (m *Lease) GetBrokerAddr() string {
	if m != nil {
		return m.BrokerAddr
	}
	return ""
}

func (m *Lease) GetExpiredTime() uint64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *Lease) GetPerm() Permission {
	if m != nil {
		return m.Perm
	}
	return Permission_READ
}

func (m *Lease) GetQueueId() uint64 {
	if m != nil {
		return m.QueueId
	}
	return 0
}

type Response struct {
	ResponseCode         Code     `protobuf:"varint,1,opt,name=responseCode,proto3,enum=batonpb.Code" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{11}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponseCode() Code {
	if m != nil {
		return m.ResponseCode
	}
	return Code_SUCCESS
}

type BrokerInfo struct {
	BrokerId             uint64   `protobuf:"varint,1,opt,name=brokerId,proto3" json:"brokerId,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerInfo) Reset()         { *m = BrokerInfo{} }
func (m *BrokerInfo) String() string { return proto.CompactTextString(m) }
func (*BrokerInfo) ProtoMessage()    {}
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8087ccb7ab16ead4, []int{12}
}

func (m *BrokerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerInfo.Unmarshal(m, b)
}
func (m *BrokerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerInfo.Marshal(b, m, deterministic)
}
func (m *BrokerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerInfo.Merge(m, src)
}
func (m *BrokerInfo) XXX_Size() int {
	return xxx_messageInfo_BrokerInfo.Size(m)
}
func (m *BrokerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerInfo proto.InternalMessageInfo

func (m *BrokerInfo) GetBrokerId() uint64 {
	if m != nil {
		return m.BrokerId
	}
	return 0
}

func (m *BrokerInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterEnum("batonpb.Action", Action_name, Action_value)
	proto.RegisterEnum("batonpb.Permission", Permission_name, Permission_value)
	proto.RegisterEnum("batonpb.Code", Code_name, Code_value)
	proto.RegisterType((*CreateTopicRequest)(nil), "batonpb.CreateTopicRequest")
	proto.RegisterType((*DeleteTopicRequest)(nil), "batonpb.DeleteTopicRequest")
	proto.RegisterType((*CreateSubscriptionRequest)(nil), "batonpb.CreateSubscriptionRequest")
	proto.RegisterType((*DeleteSubscriptionRequest)(nil), "batonpb.DeleteSubscriptionRequest")
	proto.RegisterType((*RegisterBrokerRequest)(nil), "batonpb.RegisterBrokerRequest")
	proto.RegisterType((*RegisterBrokerResponse)(nil), "batonpb.RegisterBrokerResponse")
	proto.RegisterType((*BrokerHBRequest)(nil), "batonpb.BrokerHBRequest")
	proto.RegisterType((*BrokerHBResponse)(nil), "batonpb.BrokerHBResponse")
	proto.RegisterType((*UpdateRouteRequest)(nil), "batonpb.UpdateRouteRequest")
	proto.RegisterType((*UpdateRouteResponse)(nil), "batonpb.UpdateRouteResponse")
	proto.RegisterType((*Lease)(nil), "batonpb.Lease")
	proto.RegisterType((*Response)(nil), "batonpb.Response")
	proto.RegisterType((*BrokerInfo)(nil), "batonpb.BrokerInfo")
}

func init() { proto.RegisterFile("baton.proto", fileDescriptor_8087ccb7ab16ead4) }

var fileDescriptor_8087ccb7ab16ead4 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdb, 0x6e, 0xda, 0x4a,
	0x14, 0x8d, 0xc1, 0x5c, 0xb2, 0x49, 0x88, 0xb3, 0x73, 0x4e, 0x8e, 0xc3, 0x89, 0x52, 0x34, 0x0f,
	0x0d, 0xa2, 0x6a, 0xaa, 0xd2, 0x67, 0x1e, 0x30, 0x90, 0xc6, 0x6a, 0x42, 0xe8, 0x18, 0xd4, 0xf6,
	0x29, 0x32, 0x78, 0x1a, 0x59, 0x0d, 0xd8, 0xf1, 0x45, 0xea, 0x07, 0xb4, 0xff, 0xd2, 0xcf, 0xac,
	0x66, 0x6c, 0x8c, 0x0d, 0x4e, 0x94, 0xb7, 0xd9, 0x6b, 0x2f, 0xaf, 0x7d, 0x99, 0xd1, 0x32, 0xd4,
	0x66, 0x66, 0xe0, 0x2c, 0x2f, 0x5c, 0xcf, 0x09, 0x1c, 0xac, 0x88, 0xc0, 0x9d, 0x91, 0x25, 0x60,
	0xdf, 0x63, 0x66, 0xc0, 0x26, 0x8e, 0x6b, 0xcf, 0x29, 0x7b, 0x0c, 0x99, 0x1f, 0x20, 0x82, 0xbc,
	0x34, 0x17, 0x4c, 0x95, 0x9a, 0x52, 0x6b, 0x97, 0x8a, 0x33, 0x12, 0xd8, 0x7b, 0x0c, 0x59, 0xc8,
	0x46, 0xe1, 0x62, 0xc6, 0x3c, 0x5f, 0x2d, 0x34, 0xa5, 0x56, 0x89, 0x66, 0x30, 0x6c, 0x42, 0xcd,
	0x0c, 0x03, 0xc7, 0x98, 0x9b, 0x0f, 0xf6, 0xf2, 0x5e, 0x2d, 0x36, 0xa5, 0x56, 0x95, 0xa6, 0x21,
	0xd2, 0x01, 0x1c, 0xb0, 0x07, 0xb6, 0x51, 0xef, 0x14, 0x76, 0x03, 0x1e, 0x8f, 0xd6, 0x45, 0xd7,
	0x00, 0x71, 0xe0, 0x24, 0xea, 0xd1, 0x08, 0x67, 0xfe, 0xdc, 0xb3, 0xdd, 0xc0, 0x76, 0x96, 0xcf,
	0xb5, 0x9a, 0x91, 0x2b, 0x6c, 0xc8, 0xbd, 0xa0, 0xc9, 0x77, 0x70, 0x12, 0x35, 0xf9, 0xc2, 0x82,
	0xe4, 0x0d, 0xfc, 0x4b, 0xd9, 0xbd, 0xed, 0x07, 0xcc, 0xd3, 0x3c, 0xe7, 0x07, 0xf3, 0x52, 0x64,
	0xd3, 0xb2, 0xbc, 0x15, 0x99, 0x9f, 0x49, 0x0b, 0x8e, 0x37, 0xc9, 0xbe, 0xeb, 0x2c, 0x7d, 0x86,
	0x75, 0x28, 0xd8, 0x96, 0xe0, 0xca, 0xb4, 0x60, 0x5b, 0xe4, 0x2d, 0x1c, 0x44, 0x8c, 0x2b, 0x6d,
	0x25, 0xd8, 0x80, 0xea, 0x4c, 0x40, 0xba, 0x25, 0x3a, 0x97, 0x69, 0x12, 0x93, 0x36, 0x28, 0x6b,
	0x7a, 0x2c, 0x79, 0x0c, 0x65, 0x71, 0x43, 0xbe, 0x2a, 0x35, 0x8b, 0x2d, 0x99, 0xc6, 0x11, 0x31,
	0x01, 0xa7, 0xae, 0x65, 0x06, 0x8c, 0x3a, 0x61, 0xc0, 0x56, 0xea, 0x1b, 0x0d, 0x24, 0xb3, 0x16,
	0x52, 0xcb, 0x3d, 0x87, 0xb2, 0x39, 0xe7, 0x0b, 0x11, 0xf5, 0xeb, 0x9d, 0x83, 0x8b, 0xf8, 0x2d,
	0x5d, 0xf4, 0x04, 0x4c, 0xe3, 0x34, 0xb9, 0x81, 0xa3, 0x4c, 0x89, 0xfc, 0x21, 0xf1, 0x35, 0x94,
	0x1f, 0x98, 0xe9, 0x33, 0xfe, 0xa2, 0x8a, 0xad, 0x5a, 0xa7, 0x9e, 0xe8, 0x5d, 0x73, 0x98, 0xc6,
	0x59, 0xf2, 0x47, 0x82, 0x92, 0x40, 0x32, 0x3b, 0x90, 0xb2, 0x3b, 0xc0, 0x33, 0x80, 0xe8, 0xdc,
	0xe3, 0x6b, 0x8f, 0xfa, 0x4e, 0x21, 0xfc, 0xf2, 0xd9, 0x4f, 0xd7, 0xf6, 0x98, 0x35, 0xb1, 0x17,
	0x2c, 0x5e, 0x61, 0x1a, 0xc2, 0x73, 0x90, 0x5d, 0xe6, 0x2d, 0x54, 0x59, 0x4c, 0x77, 0x94, 0x74,
	0x33, 0x66, 0xde, 0xc2, 0xf6, 0x7d, 0x3e, 0xa1, 0x20, 0xa0, 0x0a, 0x15, 0xb1, 0x4c, 0xdd, 0x52,
	0x4b, 0x42, 0x66, 0x15, 0x92, 0x2e, 0x54, 0x93, 0x71, 0xdf, 0xc3, 0x9e, 0x17, 0x9f, 0xfb, 0x8e,
	0x15, 0x3d, 0x9b, 0x7a, 0x67, 0x3f, 0x91, 0xe5, 0x20, 0xcd, 0x50, 0x88, 0x06, 0x10, 0xdd, 0xa3,
	0xbe, 0xfc, 0xee, 0x3c, 0x3b, 0xad, 0x0a, 0x15, 0xfe, 0xa4, 0x98, 0xef, 0xc7, 0xa3, 0xae, 0xc2,
	0x76, 0x03, 0xca, 0xd1, 0x75, 0x60, 0x05, 0x8a, 0xe3, 0xa9, 0xa6, 0xec, 0xf0, 0x83, 0x31, 0xd5,
	0x14, 0xa9, 0xdd, 0x05, 0x58, 0x0f, 0x83, 0x55, 0x90, 0xe9, 0xb0, 0x37, 0x50, 0x76, 0x70, 0x17,
	0x4a, 0x5f, 0xa8, 0x3e, 0x19, 0x2a, 0x12, 0xd6, 0x01, 0x38, 0x78, 0x17, 0xc5, 0x05, 0x04, 0x28,
	0x0f, 0x86, 0x23, 0x7d, 0x38, 0x50, 0x8a, 0xed, 0xdf, 0x12, 0xc8, 0xbc, 0x4f, 0xac, 0x41, 0xc5,
	0x98, 0xf6, 0xfb, 0x43, 0xc3, 0x50, 0x76, 0x38, 0xe3, 0xb2, 0xa7, 0x5f, 0x0f, 0x07, 0x8a, 0x84,
	0x87, 0xb0, 0x3f, 0xb9, 0x1d, 0xeb, 0xfd, 0xbb, 0x1b, 0xdd, 0x30, 0xf4, 0xd1, 0x47, 0xa5, 0x80,
	0x2a, 0xfc, 0x63, 0x4c, 0x35, 0xa3, 0x4f, 0xf5, 0xf1, 0x44, 0xbf, 0x1d, 0x25, 0x99, 0x22, 0xfe,
	0x07, 0x47, 0x11, 0xb9, 0x77, 0xcd, 0x4b, 0x7e, 0xbb, 0x1b, 0x7e, 0xd5, 0x8d, 0x89, 0x22, 0xe3,
	0x19, 0x34, 0x32, 0x9f, 0x64, 0xf3, 0xa5, 0xce, 0x2f, 0x19, 0x4a, 0x1a, 0xdf, 0x22, 0x76, 0xa1,
	0x96, 0x32, 0x31, 0xfc, 0x7f, 0xbd, 0xdc, 0x2d, 0x6b, 0x6b, 0x1c, 0x26, 0xc9, 0xe4, 0x8a, 0xba,
	0x50, 0x4b, 0x79, 0x52, 0xea, 0xf3, 0x6d, 0xa7, 0xca, 0xfb, 0xfc, 0xd3, 0xca, 0x42, 0xd3, 0x6e,
	0x81, 0x64, 0xa3, 0x89, 0x1c, 0x2b, 0x79, 0x42, 0x6c, 0xdb, 0x7a, 0x52, 0x62, 0x4f, 0xfa, 0x52,
	0x9e, 0xd8, 0x65, 0xe2, 0x1f, 0xcc, 0xf4, 0x02, 0x8d, 0x99, 0x01, 0xaa, 0x09, 0x6b, 0xc3, 0x59,
	0x1a, 0x27, 0x39, 0x99, 0x58, 0xe7, 0x33, 0xd4, 0xb3, 0x8e, 0x85, 0x67, 0xa9, 0x62, 0x39, 0xbe,
	0xd7, 0x78, 0xf5, 0x64, 0x3e, 0x96, 0xbc, 0x82, 0x5a, 0xca, 0x1c, 0x52, 0x3b, 0xdf, 0x76, 0xa5,
	0xc6, 0x69, 0x7e, 0x32, 0x52, 0x9a, 0x95, 0xc5, 0x1f, 0xed, 0xc3, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc8, 0xde, 0xb1, 0x24, 0xe0, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BatonClient is the client API for Baton service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BatonClient interface {
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*Response, error)
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*Response, error)
	BrokerHeartBeat(ctx context.Context, in *BrokerHBRequest, opts ...grpc.CallOption) (*BrokerHBResponse, error)
	RegisterBroker(ctx context.Context, in *RegisterBrokerRequest, opts ...grpc.CallOption) (*RegisterBrokerResponse, error)
	UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error)
}

type batonClient struct {
	cc *grpc.ClientConn
}

func NewBatonClient(cc *grpc.ClientConn) BatonClient {
	return &batonClient{cc}
}

func (c *batonClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/batonpb.Baton/CreateTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batonClient) DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/batonpb.Baton/DeleteTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batonClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/batonpb.Baton/CreateSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batonClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/batonpb.Baton/DeleteSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batonClient) BrokerHeartBeat(ctx context.Context, in *BrokerHBRequest, opts ...grpc.CallOption) (*BrokerHBResponse, error) {
	out := new(BrokerHBResponse)
	err := c.cc.Invoke(ctx, "/batonpb.Baton/BrokerHeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batonClient) RegisterBroker(ctx context.Context, in *RegisterBrokerRequest, opts ...grpc.CallOption) (*RegisterBrokerResponse, error) {
	out := new(RegisterBrokerResponse)
	err := c.cc.Invoke(ctx, "/batonpb.Baton/RegisterBroker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *batonClient) UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error) {
	out := new(UpdateRouteResponse)
	err := c.cc.Invoke(ctx, "/batonpb.Baton/UpdateRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BatonServer is the server API for Baton service.
type BatonServer interface {
	CreateTopic(context.Context, *CreateTopicRequest) (*Response, error)
	DeleteTopic(context.Context, *DeleteTopicRequest) (*Response, error)
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*Response, error)
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*Response, error)
	BrokerHeartBeat(context.Context, *BrokerHBRequest) (*BrokerHBResponse, error)
	RegisterBroker(context.Context, *RegisterBrokerRequest) (*RegisterBrokerResponse, error)
	UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error)
}

func RegisterBatonServer(s *grpc.Server, srv BatonServer) {
	s.RegisterService(&_Baton_serviceDesc, srv)
}

func _Baton_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatonServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/batonpb.Baton/CreateTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatonServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Baton_DeleteTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatonServer).DeleteTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/batonpb.Baton/DeleteTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatonServer).DeleteTopic(ctx, req.(*DeleteTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Baton_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatonServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/batonpb.Baton/CreateSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatonServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Baton_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatonServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/batonpb.Baton/DeleteSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatonServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Baton_BrokerHeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrokerHBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatonServer).BrokerHeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/batonpb.Baton/BrokerHeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatonServer).BrokerHeartBeat(ctx, req.(*BrokerHBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Baton_RegisterBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatonServer).RegisterBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/batonpb.Baton/RegisterBroker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatonServer).RegisterBroker(ctx, req.(*RegisterBrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Baton_UpdateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BatonServer).UpdateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/batonpb.Baton/UpdateRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BatonServer).UpdateRoute(ctx, req.(*UpdateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Baton_serviceDesc = grpc.ServiceDesc{
	ServiceName: "batonpb.Baton",
	HandlerType: (*BatonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTopic",
			Handler:    _Baton_CreateTopic_Handler,
		},
		{
			MethodName: "DeleteTopic",
			Handler:    _Baton_DeleteTopic_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _Baton_CreateSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _Baton_DeleteSubscription_Handler,
		},
		{
			MethodName: "BrokerHeartBeat",
			Handler:    _Baton_BrokerHeartBeat_Handler,
		},
		{
			MethodName: "RegisterBroker",
			Handler:    _Baton_RegisterBroker_Handler,
		},
		{
			MethodName: "UpdateRoute",
			Handler:    _Baton_UpdateRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baton.proto",
}
